# Generated by Django 3.2.8 on 2021-12-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='product',
        ),
        migrations.AddField(
            model_name='storage',
            name='product',
            field=models.ManyToManyField(to='app.Product'),
        ),
    ]
