# Generated by Django 3.2.8 on 2021-12-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211214_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='count',
        ),
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
