# Generated by Django 3.2.8 on 2021-12-14 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='login',
            new_name='detail',
        ),
    ]
